//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppYte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichKham
    {
        public int IDLichKham { get; set; }
        public string ChuDe { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> BatDau { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
        public string GiaoDien { get; set; }
        public Nullable<bool> LaCaNgay { get; set; }
    }
}
