//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppYte.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAppYteEntities : DbContext
    {
        public WebAppYteEntities()
            : base("name=WebAppYteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LichKham> LichKhams { get; set; }
        public virtual DbSet<Solieucovid> Solieucovids { get; set; }
        public virtual DbSet<Tintuc> Tintucs { get; set; }
    }
}
