//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppYte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solieucovid
    {
        public int IDThongkecovid { get; set; }
        public string Quocgia { get; set; }
        public Nullable<int> Socanhiem { get; set; }
        public Nullable<int> Dangdieutri { get; set; }
        public Nullable<int> Khoi { get; set; }
        public Nullable<int> Tuvong { get; set; }
        public string Ghichu { get; set; }
    }
}
