//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppYte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tintuc
    {
        public int IDTintuc { get; set; }
        public string Tieude { get; set; }
        public string Noidung { get; set; }
        public string Hinhanh { get; set; }
        public string Mota { get; set; }
        public Nullable<System.DateTime> Ngaydang { get; set; }
    }
}
